### basic settings

# site properties and page defaults
title: Visual Computing Laboratory
description: Laboratório de Computação Visual do Departamento de Computação da UFRPE.
logo: images/ufrpe-vcl-logo-ai-no-name.png
header: images/banner.jpg
footer: images/banner.jpg
baseurl: /ufrpe-vcl

# site social media and other links
links:
  email: vcl.dc@ufrpe.br
#  google-scholar: ETJoidYAAAAJ
  github: your-lab
#  twitter: YourLabHandle
  instagram: YourLabHandle
  youtube: YourLabChannel

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
